### ISSUE TITLE
Could not find file '/usr/lib/powershell/ref/System.Private.CoreLib.dll' version 0.4.7

### ISSUE THREAD

**Issue by anatoli-iliev** [cloudbase/powershell-yaml#119]
When trying to import the powershell-yaml module I am getting: **Could not find file '/usr/lib/powershell/ref/System.Private.CoreLib.dll' error.**

powershell-yaml version 0.4.7
`PS /root/.local/share/powershell/Modules/powershell-yaml/0.4.7> Import-Module powershell-yaml
Add-Type: Could not find file '/usr/lib/powershell/ref/System.Private.CoreLib.dll'.`

OS: Linux distribution Photon 4
PowerShell:
`PS /usr/lib/powershell/ref> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.3.10
PSEdition                      Core
GitCommitId                    7.3.10
OS                             Linux 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0`

Please let me know what might cause this issue?

**Comment by gabriel-samfira** [comment]
Interesting. There may be something wrong with the powershell installation on that system. It should definitely be able to find `System.Private.CoreLib.dll`. We don't really directly reference that file anywhere, but it's probably a dependency for YamlDotNet or for somethign we import in the `$stringQuotingEmitterSource`. Powershell tries to load that assembly and fails because it can't find it. It probably exists on your system, just in a different path.

If you find it and simlink it to where it expects to find it (probably along with the entire folder), it will probably work.

**Comment by gabriel-samfira** [comment]
If you're still getting this error, please try the latest pre-release:

```powershell
Install-Module -Name powershell-yaml -AllowPrerelease -Version 0.4.8-rc1 -Force
```

Closing this for now. Feel free to re-open if the issue persists.
