### ISSUE TITLE
Large number being parsed to a scientific notation

### ISSUE THREAD

**Issue by tiagovaccari** [cloudbase/powershell-yaml#128]
The simple fact of converting from yaml and converting to yaml, it changes large numbers to a scientific notation:

Example:
Before Converting from ymal
```yaml
PropertyTest: 999999999999999999999999999999999
```

After Converting to yaml
```yaml
PropertyTest: 1E+32
```

Expected:
Before Converting from ymal
```yaml
PropertyTest: 999999999999999999999999999999999
```

After Converting to yaml
```yaml
PropertyTest: 999999999999999999999999999999999
```

**Comment by gabriel-samfira** [comment]
Hi @tiagovaccari 

This seems to be due to the way powershell treats large numbers:

```powershell
PS /home/gabriel> 999999999999999999999999999999999
1E+33
```

As you can see, even without converting it in any way, powershell converts it to scientific notation. This seems to happen even with the `ConvertTo-Json` commandlets:

The `ConvertFrom-Json` commandlet seems to handle really large numbers by casting them to `[System.Numerics.BigInteger]`:

```powershell
PS /home/gabriel> $testJson = '{"num": 999999999999999999999999999999999}'
PS /home/gabriel> ConvertFrom-Json $testJson 

                              num
                              ---
999999999999999999999999999999999
```

But this seems to break when converting back to Json:

```powershell
PS /home/gabriel> ConvertFrom-Json $testJson | ConvertTo-Json
{
  "num": {
    "IsPowerOfTwo": false,
    "IsZero": false,
    "IsOne": false,
    "IsEven": false,
    "Sign": 1
  }
}
```

That being said, I implemented the `[BigInteger]` handling in powershell-yaml as well for both converting from and to yaml. You can find a WiP branch here: https://github.com/cloudbase/powershell-yaml/pull/135

I still need to add a bunch of tests.

**Comment by gabriel-samfira** [comment]
Hah. This change should help even on Windows Server 2016/Windows 10 running powershell 5.1, where the `ConvertFrom-Json` commandlet seems to convert to scientific notation:

![image](https://github.com/user-attachments/assets/14b3a2ef-de98-4a80-ba6e-213724289f48)
