### ISSUE TITLE
Array parsed as "System.Collections.Generic.List[object]"

### ISSUE THREAD

**Issue by RobDesideri** [cloudbase/powershell-yaml#15]
It is by design that array are parsed as "_System.Collections.Generic.List[object]_"?

I have some issue due this feature, for example if you test  `$parsedArray -is 'array'` PS return `false`.

Implementation: https://github.com/cloudbase/powershell-yaml/blob/a42cb50e7d40f8eadbe78aff29d3801a9a151627/powershell-yaml.psm1#L100

If you agree I can change it with a true PS array.

**Comment by gabriel-samfira** [comment]
The problem lies in the fact that when I first wrote this module, YamlDotNet was unable to serialize ```PObject``` types. That's why all the song and dance using generic objects.

A really simple way to get the result you want is explicitly casting the result as a powershell list like so:

```powershell
# Not unlike most programming languages allow you to do when defining a new
# variable
[System.Array]$ret = [System.Collections.Generic.List[object]](New-Object "System.Collections.Generic.List[object]") 
```

Unfortunately, I cannot allocate much time to this in the next few weeks. I will however investigate if a newer version of ```YamlDotNet``` will work with powershell objects (on all supported versions of powershell).

**Comment by RobDesideri** [comment]
Ok, meanwhile thanks for the tip.
