### ISSUE TITLE
Only Hashtables supported?

### ISSUE THREAD

**Issue by jlrd** [cloudbase/powershell-yaml#16]
It looks like in the help that the input object and/or the Data parameter take System.Object type but I can only seem to get ConvertTo-Yaml to work with basic hashtables.

```
$srv = Get-Service -Name BITS
ConvertTo-Yaml -Data $srv
```
Fails

```
$srv = Get-Service -Name BITS | Select-Object Name,Status,DisplayName
ConvertTo-Yaml -Data $srv
```
Fails, even as simpler object

```
$custom = [PSCustomObject]@{'Color'='Blue'; 'Day'='Monday'; Number=4}
ConvertTo-Yaml -Data $custom 
```
Fails

Only the following succeeds:
```
$hashtable = @{'Color'='Blue'; 'Day'='Monday'; Number=4}
ConvertTo-Yaml -Data $hashtable
```

Am I misunderstanding a limitation or is there any known best practices for coercing PowerShell objects into a type compatible with powershell-yaml?

Thanks!

**Comment by gabriel-samfira** [comment]
Hi @jlrd ,

Apologies for the late reply!

As the README states, this was initially written to serialize and de-serialize simple powershell objects (essentially basic types). This powershell module is a thin wrapper around YamlDotNet, which cannot handle custom types like ```System.ServiceProcess.ServiceController```, unless they are converted to something more digestible.

That being said, there is a real bug here, not being able to serialize ```PSCustomObject``` types. I just did a push with a potential fix. Would you mind cloning the ```master``` branch of the repo and trying it out to serialize a ```PSCustomObject``` ?

**Comment by jlrd** [comment]
@gabriel-samfira Thanks for taking a look at that. I just cloned master, looks like module version 0.3.1, and I am able to successfully serialize and de-serialize my PSCustomObjects from PowerShell to Yaml and back as needed. Thanks!

**Comment by gabriel-samfira** [comment]
Excelent! I will push an update to powershell gallery ASAP
