### ISSUE TITLE
Output multiple documents

### ISSUE THREAD

**Issue by felixfbecker** [cloudbase/powershell-yaml#19]
I'm wondering whether it would be possible to output multiple documents with `ConvertTo-Yaml -AllDocuments` after reading them in with `ConvertFrom-Yaml -AllDocuments`.

Essentially, this should not change the file:

```powershell
Get-Content foo.yml | ConvertFrom-Yaml -AllDocuments | ConvertTo-Yaml -AllDocuments | OutFile foo-yml
```

**Comment by gabriel-samfira** [comment]
Currently, ```ConvertFrom-Yaml``` converts multiple documents as array elements from a yaml. There is no sane way for ```ConvertTo-Yaml``` to distinguish between a normal powershell array and an array you would want to convert as a document.

I will have a look at this after the holidays. We may be able to use a different type that could easely be used to denote a document.

**Comment by felixfbecker** [comment]
Why do you need to distinguish though? With `-AllDocuments` the contract would be that `ConvertFrom-Yaml -AllDocuments` always returns multiple documents, while `ConvertTo-Yaml -AllDocuments` always takes multiple documents. The first level is always a collection of documents, after that it is always an array (or whatever else). Or is that not possible with PowerShell?

**Comment by gabriel-samfira** [comment]
Because you can have something like this in a yaml document:

```yaml
array1: [1,2,3]
array2: [4,5,6]
array3: [7,8,9]
```
This should not be congruent with a multi document yaml after it gets deserialized. This was an oversight on my part. I should have thought about this earlier.

I think it would me much cleaner to represent documents as their own type in powershell. That way you remove ambiguity, and it allows the user to know that the object they are dealing with is an actual document, not just an array element.

But I am not sure yet how to do this in the end. For now, as a quick fix "simplest" way to get the desired effect would be to save the output of ```ConvertFrom-Yaml``` in a variable, and serialize them separately. Then they can be concatenated in a file.

I know its not elegant, but after the holidays, when I get back to a computer, I can have a look at this and come back with a proper fix.

**Comment by felixfbecker** [comment]
Thanks for the reply. In that example, when parsing it with `ConvertFrom-Yaml -AllDocuments`, I would expect to get an array with only one object in it, which contains the three arrays. When it is piped into `ConvertTo-Yaml -AllDocuments`, it knows to treat the outer level as the collection of documents (with just one element) and will output the same file. Would that not be possible? (Also, feel free to not respond after the holidays :))

**Comment by gabriel-samfira** [comment]
It is indeed a possibility. But I am not a huge fan of treating types differently based on optional flags.

This needs some thought...but if the simplest and most sane way to do it is via a flag, that that will be it. I will post back as soon as I have a fix.

Cheers,
Gabriel

**Comment by felixfbecker** [comment]
Agree that changing the return type based on flags is not that nice. How about separate functions (two would just call to the other two)?
For example, https://github.com/nodeca/js-yaml has `load` and `loadAll`, where `load` returns a single document and errors if the YAML contains more than one document, while `loadAll` always returns an array of documents.

**Comment by gabriel-samfira** [comment]
I know this was open a really long time ago. Apologies for allowing this unanswered for so long. There is one option to serialize multiple documents if we add a new command line parameter that takes an list of objects as an argument.

This however may be more hassle than simply using ```ConvertTo-Yaml``` on each object and then simply concatenating the results into a string with ```---``` as separators between documents.


```powershell
PS /tmp/powershell-yaml> $myYaml = @"                            
>> ---
>>   
>> "@
PS /tmp/powershell-yaml> $myYaml += ConvertTo-Yaml $testDoc1         
PS /tmp/powershell-yaml> $myYaml += "`n---`n"                    
PS /tmp/powershell-yaml> $myYaml += ConvertTo-Yaml $testDoc2     
PS /tmp/powershell-yaml> $myYaml                            
---  
anElement: I am part of the first document

---
secondElement: I am part of the second document

PS /tmp/powershell-yaml> $myYaml | ConvertFrom-Yaml -AllDocuments
      
Name                           Value
----                           -----
anElement                      I am part of the first document
secondElement                  I am part of the second document

``` 

This means that ```powershell-yaml``` makes no assumptions about how you would like your documents serialized. If you feel this would be better as part of ```powershell-yaml``` I can add it in the next release.

**Comment by oliverroer** [comment]
I think it would be nice if the module supported creating YAML that consists of multiple documents, so that people using the module don't have to write their own code for joining the documents together as you've shown.

Either having something similar to `ConvertFrom-Yaml`s `-AllDocuments` flag...
```powershell
$Yaml = $Documents | ConvertTo-Yaml -AllDocuments
```

...or providing something along the lines of a `Join-Yaml` function that you can pipe the output into...
```powershell
$Yaml = $Documents | ConvertTo-Yaml | Join-Yaml
```

Lastly, and this is just wishful thinking, I think it would be great if there was a symmetry to the functions.
If `ConvertFrom-Yaml` can parse multiple documents, then I'd expect `ConvertTo-Yaml` to be able to do the opposite.
Or, if a `Join-Yaml` function is given, I'd expect a `Split-Yaml` function as well.
