### ISSUE TITLE
ConvertFrom-Yaml/ConvertTo-Yaml loses quotes

### ISSUE THREAD

**Issue by chrischu** [cloudbase/powershell-yaml#72]
Hi!

When converting from and the to YAML it seems as if quotes are getting lost. For example when running:
`ConvertFrom-Yaml "restart: ""no""" | ConvertTo-Yaml` the result is `restart: no` which is a problem because that turns the string `"no"` into `no` which is interpreted by YAML as a false boolean apparently.

Is there any option to change this behavior?

**Comment by gabriel-samfira** [comment]
Hi @chrischu 

First and foremost, I want to apologize for the extremely long wait on this issue. 

I created a PR here: https://github.com/cloudbase/powershell-yaml/pull/101 that should address more values that may be ambiguous. In general it shouldn't be necessary to add quotes to all string scalars. Most parsers will treat ```Plain``` scalars as strings if they cannot be cast to anything else. I've added some more values that may be considered booleans or other types to the regex in the ```StringQuotingEmitter```. This should automatically quote strings like:

  * yes
  * no
  * y
  * n
  * on
  * off
  * true
  * false 
 
Regardless of case. If you can think of any other values that may be ambiguous, feel free to add to this issue.

**Comment by chrischu** [comment]
Mhh that seems like a good workaround, but maybe it would be better to just keep quotes exactly as they are for all values? That would make it way more robust in my opinion.

What is the value of potentially removing quotes anyway?

**Comment by gabriel-samfira** [comment]
We don't really remove quotes explicitly. This is done automatically by ```YamlDotNet```. The ```powershell-yaml``` module is just a thin wrapper around that. Right now there is no easy way to round-trip a yaml (converting from yaml and then keeping it's previous properties when serializing from powershell back to yaml). This is due to the fact that we don't (yet) have a custom (de)serializer that can save or set properties on the keys and values we set in out powershell objects.

To support something like that we would need to have some way to set things like tags and scalar style in the powershell object. Something like:

```powershell
$iAmAString = "hello"
Add-Member -InputObject $iAmAString -NotePropertyMembers @{tag="tag:yaml.org,2002:str", scalarStyle="DoubleQuoted"}
``` 

Then write a custom serializer that looks at those values, builds a proper ```YamlDotNet``` object which is then serialized. It's doable, but not something I have time for right now.

For now, simply disambiguating the values and quoting them explicitly when needed, should have the same effect for this particular use case.

**Comment by chrischu** [comment]
Ok I understand, at least it fixes the current problem :). Thanks!
