### ISSUE TITLE
Missing double quotes after conversion

### ISSUE THREAD

**Issue by ckrueger1979** [cloudbase/powershell-yaml#82]
Hi,

after converting to YAML the double quotes for the value are missing.

```
$yaml=@'
hello: "world:test"
'@

ConvertFrom-Yaml $yaml

Name                           Value
----                           -----
hello                          world:test

ConvertFrom-Yaml $yaml | convertto-yaml
hello: world:test
      ^^         ^^
```

As far as I understand the idea of StringQuotingEmitter this should be prevented but it doesn't.

Any idea how to fix?

greetings
Carsten

**Comment by gabriel-samfira** [comment]
Hi @ckrueger1979 !

It has been an embarrassingly long time since you open this and I have not responded. My apologies!

The point of the ```StringQuotingEmitter``` was to set double quotes around strings that had the potential to be ambiguous. For example:

```powershell
PS /home/gabriel> $yaml=@'                    
>> hello: "11111"          
>> '@
PS /home/gabriel> ConvertFrom-Yaml $yaml      

Name                           Value
----                           -----
hello                          11111

PS /home/gabriel> ConvertFrom-Yaml $yaml | cty
hello: "11111"
```

Values that run the risk to be automatically cast to an improper type when unmarshaled from yaml (in the absence of tags), were placed in quotes to prevent situations where doing something like:

```powershell
ConvertFrom-Yaml $yaml | ConvertTo-Yaml | ConvertFrom-Yaml
```

would turn ```"1111"``` (```[string]```) into ```1111``` (```[int]```).

The value ```world:test``` cannot be mistaken for any other type than ```[string]```, so quotes are not added.

As a side note, we have recently [merged tag support](https://github.com/cloudbase/powershell-yaml/pull/100 ). It is generally a good idea to use tags when you want to make sure that the value ends up with its intended type once unserialized (regardless of whether or not it's quoted.

```powershell
PS /home/gabriel> $yaml=@'                               
>> helloString: !!str 11111
>> helloInt: 1111
>> '@
PS /home/gabriel> ConvertFrom-Yaml $yaml | ConvertTo-Yaml
helloInt: 1111
helloString: "11111"
```
