### ISSUE TITLE
Converting From Yaml but the Input is a variable with a file content

### ISSUE THREAD

**Issue by Guillem2607** [cloudbase/powershell-yaml#92]
I'm trying to convert a yaml file to a hastable for manage the objects that contain, like "Installers".

The content is a yaml file content, so it shouldn't having any problem with that. I attach some photos with the content of the file and the error that I'm having.

![yamlcontent](https://user-images.githubusercontent.com/121028740/208418807-4aca6c29-5264-459f-90a6-388749e75ae2.PNG)

![varyaml](https://user-images.githubusercontent.com/121028740/208417858-61794b1c-4ee8-43a3-bb80-ddf992d85e96.PNG)

PD: The content of the file that I'm managing is posted in [winget repository, here in github](https://raw.githubusercontent.com/microsoft/winget-pkgs/master/manifests/7/7zip/7zip/22.01/7zip.7zip.installer.yaml)

**Comment by Guillem2607** [comment]
So 20 minutes after I posted this issue I have thrown a triple chasing some solution and I found it, I get the file content at the same time as I convert the variable from yaml to a hashtable.

![solution](https://user-images.githubusercontent.com/121028740/208423104-97c70928-25b9-4af8-b7cd-d2aa77fb7e0d.PNG)

**Comment by gabriel-samfira** [comment]
A bit of context to what happened in the first one. When you use ```Get-Content``` without the ```-Raw``` parameter, you get an array of objects. Essentially, an array of lines inside the yaml file.

When you use the ```-Raw``` flag, all the contents of the file is read at once as a raw string.

The ```powershell-yaml``` module uses "Advanced functions" which allows us to specify a ```BEGIN```, ```PROCESS``` and ```END``` blocks. We use this to read a stream sent through a pipe and in the ```END``` block we process all input as a single ```yaml```. This is why piping the contents of ```Get-Content``` works, but not sending it as a parameter.

To illustrate, we'll use the following ```yaml```:

```yaml
hi: there
goodbye: now
```

Using ```Get-Content``` without ```-Raw```:

```powershell
$contents = Get-Content /tmp/test.yaml
PS /tmp> $contents                             
hi: there
goodbye: now
```


Let's see what we got:

```powershell
PS /tmp> $contents.GetType().FullName
System.Object[]
```
As we can see, this is an array of objects, not a string. If we try to pass it as a positional parameter, ```ConvertFrom-Yaml``` will try to convert from string to powershell objects, so we'll get an error:

```powershell
PS /tmp> ConvertFrom-Yaml $contents
ConvertFrom-Yaml: Cannot process argument transformation on parameter 'Yaml'. Cannot convert value to type System.String.
# but if we pipe it
```

But piping the same object, will work due to how the  ```BEGIN```, ```PROCESS```, ```END``` workflow works:

```powershell
PS /tmp> $contents | ConvertFrom-yaml          

Name                           Value
----                           -----
hi                             there
goodbye                        now
```

To save yourself the headache, simply use the ```-Raw``` flag when you use ```Get-Content```:

```powershell
PS /tmp> $contents = Get-Content -Raw /tmp/test.yaml
PS /tmp> $contents.GetType().FullName
System.String
PS /tmp> ConvertFrom-Yaml $contents

Name                           Value
----                           -----
hi                             there
goodbye                        now

PS /tmp> $contents | ConvertFrom-Yaml

Name                           Value
----                           -----
hi                             there
goodbye                        now
```

**Comment by gabriel-samfira** [comment]
Also, if ordering is important, use the ```-Ordered``` flag when using ```ConvertFrom-Yaml```.
